### ISSUE TITLE
Upgrade To 0.9  from 0.8 erro

### ISSUE THREAD

**Issue by purwadarozatun** [laravolt/epicentrum#1]
When I upgrade to 0.9  from 0.8 or fresh install there is an error when accessing role and user menu in epicentrum module.

I Belive there issue in $this->authorize('manage-role'); 
I cahange to  $this->middleware('can:manage-role');

is there a concern when using authorize ? 
Some Screenshoot : 
![2017-06-01 20_21_41-localhost_8000_master_data_roles_1_edit](https://cloud.githubusercontent.com/assets/8139599/26681623/f6602a56-4707-11e7-8b26-fedbdc0274d5.png)
 $this->authorize('manage-role'); 

![2017-06-01 20_23_03-welcome home _ cleo](https://cloud.githubusercontent.com/assets/8139599/26681690/30f6d700-4708-11e7-8df7-6f082dd10f3a.png)

I cahange to  $this->middleware('can:manage-role');

**Comment by uyab** [comment]
Thanks for reporting, fixed in 0.10.
